# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: servicewell.fhir.frenda-wof-connect-flc
canonical: https://canonical.fhir.link/servicewell/fhir.frenda-wof-connect-flc
name:  servicewell.fhir.frenda-wof-connect-flc
title: Frenda Wof-Connect FLC
description: Service Well’s FHIR Liquid Conversion (FLC) implementation for Frenda to WOF Connect, enabling template-driven transformation of Frenda data into standards-compliant FHIR
status: draft # draft | active | retired | unknown
version: 0.1.2
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build [WIP]
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: Service Well AB
  url: https://servicewell.se
  # email: test@example.org

# The dependencies property corresponds to IG.dependsOn. The key is the
# package id and the value is the version (or dev/current). For advanced
# use cases, the value can be an object with keys for id, uri, and version.
#
dependencies:
  ihe.iti.scheduling: 1.0.0
  hl7.fhir.uv.extensions.r4: 5.2.0
  flc.fhir.base: 0.2.3
  servicewell.fhir.wof-connect: current

#
#
# The pages property corresponds to IG.definition.page. SUSHI can
# auto-generate the page list, but if the author includes pages in
# this file, it is assumed that the author will fully manage the
# pages section and SUSHI will not generate any page entries.
# The page file name is used as the key. If title is not provided,
# then the title will be generated from the file name.  If a
# generation value is not provided, it will be inferred from the
# file name extension.  Any subproperties that are valid filenames
# with supported extensions (e.g., .md/.xml) will be treated as
# sub-pages.
#
# pages:
#   index.md:
#     title: Example Home
#   implementation.xml:
#   examples.xml:
#     title: Examples Overview
#     simpleExamples.xml:
#     complexExamples.xml:
#
#
# The parameters property represents IG.definition.parameter. Rather
# than a list of code/value pairs (as in the ImplementationGuide
# resource), the code is the YAML key. If a parameter allows repeating
# values, the value in the YAML should be a sequence/array.
# For parameters defined by core FHIR see:
# http://build.fhir.org/codesystem-guide-parameter-code.html
# For parameters defined by the FHIR Tools IG see:
# http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html
#
parameters:
  path-binary: [input\flc\templates, input\flc\sampledata, input\flc\templates\codesystem, input\flc\templates\resources, input\flc\templates\id, input\flc\examples, input\flc\templates\variables]
  excludettl: true
#   validation: [allow-any-extensions, no-broken-links]
#
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │ The menu property will be used to generate the input/menu.xml file. The menu is represented    │
# │ as a simple structure where the YAML key is the menu item name and the value is the URL.       │
# │ The IG publisher currently only supports one level deep on sub-menus. To provide a             │
# │ custom menu.xml file, do not include this property and include a `menu.xml` file in            │
# │ input/includes. To use a provided input/includes/menu.xml file, delete the "menu"              │
# │ property below.                                                                                │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html

# ╭───────────────────────────Less Common Implementation Guide Properties──────────────────────────╮
# │  Uncomment the properties below to configure additional properties on the ImplementationGuide  │
# │  resource. These properties are less commonly needed than those above.                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
#
# Those who need more control or want to add additional details to the contact values can use
# contact directly and follow the format outlined in the ImplementationGuide resource and
# ContactDetail.
#
# contact:
#   - name: Bob Smith
#     telecom:
#       - system: email # phone | fax | email | pager | url | sms | other
#         value: bobsmith@example.org
#         use: work
#
#
# The global property corresponds to the IG.global property, but it
# uses the type as the YAML key and the profile as its value. Since
# FHIR does not explicitly disallow more than one profile per type,
# neither do we; the value can be a single profile URL or an array
# of profile URLs. If a value is an id or name, SUSHI will replace
# it with the correct canonical when generating the IG JSON.
#
# global:
#   Patient: http://example.org/fhir/StructureDefinition/my-patient-profile
#   Encounter: http://example.org/fhir/StructureDefinition/my-encounter-profile
#
#
# The resources property corresponds to IG.definition.resource.
# SUSHI can auto-generate all of the resource entries based on
# the FSH definitions and/or information in any user-provided
# JSON or XML resource files. If the generated entries are not
# sufficient or complete, however, the author can add entries
# here. If the reference matches a generated entry, it will
# replace the generated entry. If it doesn't match any generated
# entries, it will be added to the generated entries. The format
# follows IG.definition.resource with the following differences:
#   * use IG.definition.resource.reference.reference as the YAML key.
#   * if the key is an id or name, SUSHI will replace it with the
#     correct URL when generating the IG JSON.
#   * specify "omit" to omit a FSH-generated resource from the
#     resource list.
#   * if the exampleCanonical is an id or name, SUSHI will replace
#     it with the correct canonical when generating the IG JSON.
#   * groupingId can be used, but top-level groups syntax may be a
#     better option (see below).
# The following are simple examples to demonstrate what this might
# look like:
#
resources:
# FLC AUTO START input\flc\sampledata
  Appointment/5052cc88-45ed-4c89-9d02-94e1fef79483:
    name: GetAppointmentById
    description: Generated from template GetAppointmentById.liquid
    exampleBoolean: true
  Bundle/e501427c-0801-e520-474d-e1748c84bcae:
    name: GetAppointmentsByPatient-All
    description: Generated from template GetAppointmentsByPatient.liquid
    exampleBoolean: true
  Bundle/cb308bcf-4383-edf1-ee0a-a6c9ec4bbeb1:
    name: GetAppointmentsByPatient-ByClinic
    description: Generated from template GetAppointmentsByPatient.liquid
    exampleBoolean: true
  Bundle/c483eca8-e7af-b936-6601-b744ba70df44:
    name: GetClinicTreatments
    description: Generated from template GetClinicTreatments.liquid
    exampleBoolean: true
  Patient/af1019ec-4d10-349e-7efb-688ab2bd2553:
    name: GetPatientDetails
    description: Generated from template GetPatientDetails.liquid
    exampleBoolean: true
  Bundle/65c9ca1d-fa59-70a1-bea9-e781481692e4:
    name: GetSlots-Reschedule
    description: Generated from template GetAppointmentFindOp.liquid
    exampleBoolean: true
  Bundle/c8fb8359-ebb5-dfc9-0910-02a2489b91f9:
    name: GetSlots
    description: Generated from template GetAppointmentFindOp.liquid
    exampleBoolean: true
  Bundle/3dab394b-fbba-ce5d-ca14-aa369573682e:
    name: PostCreateAppointment-Cancel
    description: Generated from template AppointmentBookOpResult.liquid
    exampleBoolean: true
  Bundle/2da62793-f516-e2d8-caa8-b628a31c52f8:
    name: PostCreateAppointment-Create
    description: Generated from template AppointmentBookOpResult.liquid
    exampleBoolean: true
  Bundle/3171d045-b561-935b-18cf-4c4f53139189:
    name: PostCreateAppointment-Update
    description: Generated from template AppointmentBookOpResult.liquid
    exampleBoolean: true
# FLC AUTO END input\flc\sampledata
instanceOptions:
  # When set to true, slices must be referred to by name and not only by a numeric index in order to be used
  # in an Instance's assignment rule. All slices appear in the order in which they are specified in FSH rules.
  # While SUSHI defaults to false for legacy reasons, manualSliceOrding is recommended for new projects.
  manualSliceOrdering: true # true | false
  # Determines for which types of Instances SUSHI will automatically set meta.profile
  # if InstanceOf references a profile:
  #
  # setMetaProfile: always # always | never | inline-only | standalone-only
  #
  #
  # Determines for which types of Instances SUSHI will automatically set id
  # if InstanceOf references a profile:
  #
  # setId: always # always | standalone-only
