trigger: none

resources:
  repositories:
    - repository: PublishTemplate
      name: swts/servicewell.fhir.landingzone
      type: git
      ref: refs/heads/main
      endpoint: cross-project-connection
    - repository: IGSource
      name: servicewell/servicewell.fhir.se.frenda-wof-connect-flc
      type: github
      ref: refs/heads/main
      endpoint: IG Github Connection

pool:
  name: 'Implementation Guide Build Pool'

jobs:
  - job: SetupPublish
    steps:
      - checkout: IGSource
        persistCredentials: true
        path: ig
        workspaceRepo: true

      - script: |
          set -euo pipefail
          ORG=$(yq e -e -r '.id' "$(System.DefaultWorkingDirectory)/sushi-config.yaml" | cut -d'.' -f1)
          test -n "$ORG"
          echo "##vso[task.setvariable variable=org]$ORG"
        displayName: Detect organization from sushi-config

      - template: ".azure-pipelines/ig-templates/ig-publish-template.yaml@PublishTemplate"
        parameters:
          organization: $(org)
